spring.application.name=nexus-employee-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr_db
spring.datasource.username=postgres
spring.datasource.password=vidyadb123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER CONFIG
# ===============================

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

# ===============================
# REDIS CONFIG
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6380

# ===============================
# LOGGING (OPTIONAL - DEBUGGING)
# ===============================
logging.level.org.springframework=INFO
logging.level.com.zidio=DEBUG

# ===============================
# SSE (OPTIONAL)
# ===============================
spring.mvc.async.request-timeout=3600000