spring.application.name=nexus-employee-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr_db
spring.datasource.username=postgres
spring.datasource.password=vidyadb123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

nexus.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
nexus.jwt.expiration=86400000