spring.application.name=nexus-auth-service
server.port=8081

# PostgreSQL Connection - Added SSL disable and cleanup
spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr_db?sslmode=disable
spring.datasource.username=devjashani
spring.datasource.password=jashaniji21
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Hibernate 6+ doesnt strictly need the dialect property, 
# but if you keep it, ensure it's exactly this:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Critical: Isse humein asali error console par dikhega
logging.level.org.hibernate.tool.schema=DEBUG

# Debugging ke liye ye add karo, isse terminal bata dega request kahan ruk rahi hai
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.main.allow-circular-references=true

# Add these for better debugging
logging.level.com.zidio.nexushr=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always

# Security: JWT Configuration
nexus.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
nexus.jwt.expiration=86400000